receivers:
  otlp:
    protocols:
      grpc:
exporters:
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
    tls:
      insecure: true
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - zipkin
        - otlp
